# image: node:alpine
# image: alpine:latest
image: node:12.9.0
variables:
  PUBLIC_URL: /spacecraftreact
# Cache node modules - speeds up future builds
# cache:
  # paths:
    # - node_modules
stages:
  - build
  - deploy

before_script:
  # - apk add nodejs
  # - apk add npm
  # - apk add curl
  # - apk add sudo
  # - apk add bash
  # - npm install -g npm@latest
  - npm config set unsafe-perm=true
  - npm install -g firebase-tools --unsafe-perm=true --allow-root
  - npm install --unsafe-perm=true --allow-root # Install all dependencies

# build phase  
build:
  stage: build
  script:
    - npm run build --prod # Build for prod

netlify:
  stage: deploy
  script:
    - echo "deploy to netlify"
  environment:
    name: staging
    url: https://spacecraftreact.netlify.com
  only:
    - master
firebase_hosting:
  stage: deploy
  script:
    - echo "deploy to firebase hosting"
    - firebase deploy --only hosting --token $FIREBASE_TOKEN
  environment:
    name: production
    url: https://staging.example.com
  only:
    - master
# Job name for gitlab to recognise this results in assets for Gitlab Pages
# https://docs.gitlab.com/ee/user/project/pages/introduction.html#gitlab-pages-requirements
pages:
  stage: deploy
  script:
    - echo "deploy to gitlab pages"
    - cp public/index.html public/404.html # Not necessary, but helps with https://medium.com/@pshrmn/demystifying-single-page-applications-3068d0555d46
    - mv public _public # CRA and gitlab pages both use the public folder. Only do this in a build pipeline.
    - mv build public # Move build files to public dir for Gitlab Pages
  artifacts:
    paths:
    - public # The built files for Gitlab Pages to serve
  only:
    - master # Only run on master branch
 