image: node:alpine
# variables:
#   PUBLIC_URL: /spacecraftreact
# Cache node modules - speeds up future builds
cache:
  paths:
    - node_modules
stages:
  - build
#   - cleanup_build
  - test
  - deploy
  - staging
  - production
  - perfomance

before_script:
  - echo "global before script"
after_script:
  - echo "global after script"
  
# build phase  
build_dependencies:
  stage: build
  script: echo "running build dependencies script"

build_artifacts:
  stage: build
  script: echo "running build artifacts script"

# cleanup_build_job:
#   stage: cleanup_build
#   script:
#     - echo "cleanup build when failed"
#   when: on_failure
# test phase
code_quality:
  stage: build
  script: echo "running code quality script"

dependency_scanning:
  stage: build
  script: echo "running dependency scanning script"
 
sast:
  stage: build
  script: echo "running static application security testing script"
  
sast_container:
  stage: build
  script: echo "running contanier script"
test:
  stage: build
  script: echo "running test script"
# staging phase
staging:
  stage: staging
  script:
    - echo "running staging script"

# deploy phose
deploy_staging:
  stage: deploy
  script:
    - echo "Deploy to staging server"
  environment:
    name: staging
    url: https://staging.example.com
  only:
  - master

#performance

  
# Job name for gitlab to recognise this results in assets for Gitlab Pages
# https://docs.gitlab.com/ee/user/project/pages/introduction.html#gitlab-pages-requirements
pages:
  stage: deploy
  script:
    - echo "Deploy to gitlab page"
    - npm install # Install all dependencies
    - npm run build --prod # Build for prod
    - cp public/index.html public/404.html # Not necessary, but helps with https://medium.com/@pshrmn/demystifying-single-page-applications-3068d0555d46
    - mv public _public # CRA and gitlab pages both use the public folder. Only do this in a build pipeline.
    - mv build public # Move build files to public dir for Gitlab Pages
  artifacts:
    paths:
    - public # The built files for Gitlab Pages to serve
  only:
    - master # Only run on master branch

 