image: node:alpine
# variables:
#   PUBLIC_URL: /spacecraftreact
# Cache node modules - speeds up future builds
cache:
  paths:
    - node_modules
stages:
  - build
  - cleanup_build
  - test
  - deploy
  - cleanup

before_script:
  - echo "global before script"
script:
  - echo "running global script"
after_script:
  - echo "global after script"

# Job name for gitlab to recognise this results in assets for Gitlab Pages
# https://docs.gitlab.com/ee/user/project/pages/introduction.html#gitlab-pages-requirements
pages:
  stage: deploy
  script:
    - echo "Deploy to gitlab page"
    - npm install # Install all dependencies
    - npm run build --prod # Build for prod
    - cp public/index.html public/404.html # Not necessary, but helps with https://medium.com/@pshrmn/demystifying-single-page-applications-3068d0555d46
    - mv public _public # CRA and gitlab pages both use the public folder. Only do this in a build pipeline.
    - mv build public # Move build files to public dir for Gitlab Pages
  artifacts:
    paths:
    - public # The built files for Gitlab Pages to serve
  only:
    - master # Only run on master branch
# ====================================example start===========================================
job 1:
  stage: build
  script: echo "job 1>>running build dependencies script"

job 2:
  stage: build
  script: echo "running build artifacts script"

job 3:
  stage: test
  script: echo "running test script"

job 4:
  stage: deploy
  script: echo "running test script"

cleanup_build_job:
  stage: cleanup_build
  script:
    - cleanup build when failed
  when: on_failure

test_job:
  stage: test
  script:
    - make test

build_job:
  stage: build
  script:
    - make build
    
deploy_job:
  stage: deploy
  script:
    - make deploy
  when: manual

cleanup_job:
  stage: cleanup
  script:
    - cleanup after jobs
  when: always

deploy_staging:
  stage: deploy
  script:
    - echo "Deploy to staging server"
  environment:
    name: staging
    url: https://staging.example.com
  only:
  - master
# ====================================example end===========================================
 