# image: node:alpine
image: node:12.13.0-alpine
# image: "python:2.7"

variables:
  PUBLIC_URL: /spacecraftreact
# Cache node modules - speeds up future builds
# cache:
  # paths:
    # - node_modules
stages:
  - build
  - deploy

before_script:
  - apt-get -yq update
  - apt-get -yq install software-properties-common
  - add-apt-repository -y ppa:deadsnakes/ppa
  - apt-get -yq install python-minimal python2.7 python2.7-dev python3.6 python3.6-dev python3.7 python3.7-dev python-pip
  - npm cache clean --force
  - rm -rf node_modules
  - npm install -g npm@latest
  - npm install -g grpc@1.20.0
  - npm install --global node-gyp
  - npm i core-util-is
  - npm i -g firebase-tools
  - npm install # Install all dependencies

# build phase  
build:
  stage: build
  script:
    - npm run build --prod # Build for prod

netlify:
  stage: deploy
  script:
    - echo "deploy to netlify"
  environment:
    name: staging
    url: https://staging.example.com
  only:
    - master
firebase_hosting:
  stage: deploy
  script:
    - echo "deploy to firebase hosting"
    - firebase deploy --only hosting --token $FIREBASE_TOKEN
  environment:
    name: production
    url: https://staging.example.com
  only:
    - master
# Job name for gitlab to recognise this results in assets for Gitlab Pages
# https://docs.gitlab.com/ee/user/project/pages/introduction.html#gitlab-pages-requirements
pages:
  stage: deploy
  script:
    - echo "deploy to gitlab pages"
    - cp public/index.html public/404.html # Not necessary, but helps with https://medium.com/@pshrmn/demystifying-single-page-applications-3068d0555d46
    - mv public _public # CRA and gitlab pages both use the public folder. Only do this in a build pipeline.
    - mv build public # Move build files to public dir for Gitlab Pages
  artifacts:
    paths:
    - public # The built files for Gitlab Pages to serve
  only:
    - master # Only run on master branch
 